# Linear Algebra using NumPy

Numpy - NumPy is the fundamental package for scientific computing with Python. Visit https://www.numpy.org/ for more

## Table of Contents
- [Scalars](#scalars)
- [Vectors](#vectors)
    - [dtype](#dtype)
    - [Vector Operations](#vector-operations)
- [Matrices](#matrices)
    - [Matrix Operations](#matrix-operations)
    - [Matrix Reshape](#matrix-reshape)
    - [Special Matrices](#special-matrices)
        - [Identity Matrices or Unit Matrices](#identity-matrices)
        - [Diagonal Matrices](#diagonal-matrices)
        - [Zero Matrix](#zero-matrix)
        - [Orthogonal Matrices](#orthogonal-matrices)
    - [Matrix Inverse](#matrix-inverse)
    - [Matrix Product](#matrix-product)
    - [Matrix and Vector norms](#matrix-vector-norms)
    - [Eigendecomposition](#eigendecomposition)
    - [Matrix Trace](#matrix-trace)
    - [Matrix Gradient](#matrix-gradient)
    - [Hessian Matrix](#matrix-hessian)
- [Resources](#resources)

In [1]:
import numpy as np

## Scalars  <a class="anchor" id="scalars"></a>

More here:
- https://en.wikipedia.org/wiki/Scalar_(mathematics)

A scalar is an element of a field which is used to define a vector space. 
Scalars represent ordinary numbers. Nothing special.
All basic math rules and operations apply for scalars.

In [2]:
# Scalars are usually written down in lowercase in code

scalar = 3
print ("Variable \'scalar\' is equal to", scalar)

a = 2
b = 6
print (a*b)
print (a/b)
print (a+b)
print (a-b)

Variable 'scalar' is equal to 3
12
0.3333333333333333
8
-4


## Vectors <a class="anchor" id="vectors"></a>

More here:
- https://en.wikipedia.org/wiki/Vector_(mathematics_and_physics)

In mathematics a vector is an element of a vector space.

A vector space (also called a linear space) is a collection of objects called vectors, which may be added together and multiplied ("scaled") by numbers, called scalars. 
Scalars are often taken to be real numbers, but there are also vector spaces with scalar multiplication by complex numbers, rational numbers, or generally any field.


In [3]:
# Vectors are usually written down in lowercase in code

# Example: Vector defined as Vector
vector = np.array([1,2,3], np.int)
print ("Vector Value:", vector)
print ("Vector Shape:", vector.shape)

print ("Notation Type: [rows? or columns?]. Sounds like a missing dimension!")
print ("Container Type:", format(type(vector)))
print ("Container Data Type:", format(vector.dtype))

print ("----------------------------------------")

# Example: Vector defined as List of Vectors, e.g: Matrix
# It's preferable to define Vectors like this due to more verbose outputs
# Pay attention to Vector Shape output difference

vector2 = np.array([[-1,-2,-3]], np.int)
print ("Vector Value:", vector2)
print ("Vector Shape:", vector2.shape)

print ("Notation Type: [rows, columns]")
print ("Container Type:", format(type(vector2)))
print ("Container Data Type:", format(vector2.dtype))


Vector Value: [1 2 3]
Vector Shape: (3,)
Notation Type: [rows? or columns?]. Sounds like a missing dimension!
Container Type: <class 'numpy.ndarray'>
Container Data Type: int32
----------------------------------------
Vector Value: [[-1 -2 -3]]
Vector Shape: (1, 3)
Notation Type: [rows, columns]
Container Type: <class 'numpy.ndarray'>
Container Data Type: int32


### dtype <a class="anchor" id="dtype"></a>
More on Python and NumPy datatypes (dtype), second argument in above array function:
- https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.dtypes.html

In [4]:
# Column Vectors can also be created

column = np.array([[.25],[.50],[.75],[1]])
print ("Column vector:\n", column)
print ("Column vector shape:", column.shape)

Column vector:
 [[0.25]
 [0.5 ]
 [0.75]
 [1.  ]]
Column vector shape: (4, 1)


### Vector operations <a class="anchor" id="vector-operations"></a>

Transpose

In linear algebra, the transpose of a matrix is an operator which flips a matrix over its diagonal, that is it switches the row and column indices of the matrix by producing another matrix denoted as A<sup>T</sup> (also written A′, A<sup>tr</sup>, <sup>t</sup>A or A<sup>t</sup>). It is achieved by any one of the following equivalent actions:

 - reflect A over its main diagonal (which runs from top-left to bottom-right) to obtain A<sup>T</sup>,
 - write the rows of A as the columns of A<sup>T</sup>,
 - write the columns of A as the rows of A<sup>T</sup>.

If A is an <i>m × n</i> matrix, then A<sup>T</sup> is an <i>n × m</i> matrix.

In [5]:
print ("Column vector:\n", column, "and shape: ", column.shape, "\n\n\nColumn vector transpose:\n", column.T, "and shape:", column.T.shape)

print ("----------------------------------------")
print ("One way to transpose is:", np.transpose(column))
print ("The other one, cosider this as a syntactc sugar is:", column.T)

Column vector:
 [[0.25]
 [0.5 ]
 [0.75]
 [1.  ]] and shape:  (4, 1) 


Column vector transpose:
 [[0.25 0.5  0.75 1.  ]] and shape: (1, 4)
----------------------------------------
One way to transpose is: [[0.25 0.5  0.75 1.  ]]
The other one, cosider this as a syntactc sugar is: [[0.25 0.5  0.75 1.  ]]


## Matrices <a class="anchor" id="matrices"></a>

In mathematics, a matrix is a rectangular array of numbers, symbols, or expressions, arranged in rows and columns.

More here:
- https://en.wikipedia.org/wiki/Matrix_(mathematics)

In [6]:
# Matrices are usually written down in uppercase in code

MATRIX = np.array([[1,2,3], [5,6,7]])
print ("Matrix example:\n", MATRIX)
print ("Matrix shape:", MATRIX.shape)
print('Continer Data Type: {0}'.format(MATRIX.dtype))

Matrix example:
 [[1 2 3]
 [5 6 7]]
Matrix shape: (2, 3)
Continer Data Type: int32


### Matrix Operations <a class="anchor" id="matrix-operations"></a>

In [7]:
# Transpose
# The same way as with vectors

print ("Transposed matrix:\n", MATRIX.T)

Transposed matrix:
 [[1 5]
 [2 6]
 [3 7]]


In [8]:
# Getting elements
# Note: MATRIX is not a transposed object here! MATRIX.T returns new value, and does not overwrite itself!

print ("Original matrix:\n", MATRIX)
print ("Getting matrix value by index, index starts from zero:", MATRIX.item(3))
print ("Getting matrix value by index, using tuples (row, column):", MATRIX.item(1,2))

Original matrix:
 [[1 2 3]
 [5 6 7]]
Getting matrix value by index, index starts from zero: 5
Getting matrix value by index, using tuples (row, column): 7


Getting rows and columns is easy using Python slices. More on this here: 
- http://structure.usc.edu/numarray/node26.html
- https://docs.python.org/2.3/whatsnew/section-slices.html

In [9]:
# Getting rows

print ("Original matrix:\n", MATRIX)
print ("Second row:", MATRIX[1,:])

Original matrix:
 [[1 2 3]
 [5 6 7]]
Second row: [5 6 7]


In [10]:
# Getting columns

print ("Original matrix:\n", MATRIX)
print ("Third row:", MATRIX[:,2])

Original matrix:
 [[1 2 3]
 [5 6 7]]
Third row: [3 7]


### Matrix reshape <a class="anchor" id="matrix-reshape"></a>
More info here:
- https://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html

More info on Tensors:
- https://en.wikipedia.org/wiki/Tensor

Basically Vectors and Matrices are partial cases of Tensors

In [11]:
# random.rand(N) will give N randomly uniformly distributed values in [0,1) range
RANDOM_LIST = np.random.rand(12)
print ("Randomly generated list:\n", RANDOM_LIST, "\n")

# Reshape v1
RES_v1 = RANDOM_LIST.reshape(3,4)
print ("Reshaped list into matrix:\n", RES_v1, "\n")

#Reshape v2
RES_v2 = RANDOM_LIST.reshape(3,2,2)
print ("Reshaped list into tensor:\n", RES_v2)

# Note: Multiplying values inside LIST.reshape() function MUST be equal to original list dimension!

Randomly generated list:
 [0.09704602 0.6492746  0.30920394 0.37308471 0.43696849 0.50677287
 0.09254658 0.26382981 0.11637229 0.47225671 0.18728658 0.30041128] 

Reshaped list into matrix:
 [[0.09704602 0.6492746  0.30920394 0.37308471]
 [0.43696849 0.50677287 0.09254658 0.26382981]
 [0.11637229 0.47225671 0.18728658 0.30041128]] 

Reshaped list into tensor:
 [[[0.09704602 0.6492746 ]
  [0.30920394 0.37308471]]

 [[0.43696849 0.50677287]
  [0.09254658 0.26382981]]

 [[0.11637229 0.47225671]
  [0.18728658 0.30041128]]]


### Special Matrices <a class="anchor" id="special-matrices"></a>

### Identity Matrices or Unit Matrices <a class="anchor" id="identity-matrices"></a>
More info:
- https://en.wikipedia.org/wiki/Identity_matrix


In [12]:
I_MATRIX = np.identity(5, np.int32)
print ("Building identity matrix:")
print (I_MATRIX, "\n")

print ("Building Eye matrix with diagonal shift:")
E_MATRIX = np.eye(5, k=2, dtype = np.int32) # k - defines shift of a diagonal
print (E_MATRIX)

Building identity matrix:
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]] 

Building Eye matrix with diagonal shift:
[[0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]
 [0 0 0 0 0]
 [0 0 0 0 0]]


### Diagonal Matrices <a class="anchor" id="diagonal-matrices"></a>

More info:
- https://en.wikipedia.org/wiki/Diagonal_matrix
- https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.diag.html

In [13]:
D_MATRIX = np.array([[1,0,0], [0,2,0], [0,0,3]])

print ("Diagonal Matrix:\n", D_MATRIX, "\n")

print ("Getting main diagonal of a matrix:\n", D_MATRIX.diagonal())
print ("Getting 1st diagonal of a matrix:\n", D_MATRIX.diagonal(1))
print ("Getting -1st diagonal of a matrix:\n", D_MATRIX.diagonal(-1))

print ("Getting main diagonal of a matrix (second approach):\n", np.diag(D_MATRIX))
print ("Getting 1st diagonal of a matrix (second approach):\n", np.diag(D_MATRIX, 1))

Diagonal Matrix:
 [[1 0 0]
 [0 2 0]
 [0 0 3]] 

Getting main diagonal of a matrix:
 [1 2 3]
Getting 1st diagonal of a matrix:
 [0 0]
Getting -1st diagonal of a matrix:
 [0 0]
Getting main diagonal of a matrix (second approach):
 [1 2 3]
Getting 1st diagonal of a matrix (second approach):
 [0 0]


### Zero Matrix or Null Matrix <a class="anchor" id="zero-matrix"></a>

More info:
- https://en.wikipedia.org/wiki/Zero_matrix

In [14]:
Z_MATRIX = np.zeros((4,4), dtype = np.int32)
print ("Newly created null matrix:\n", Z_MATRIX)

Newly created null matrix:
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


### Orthogonal Matrices <a class="anchor" id="orthogonal-matrices"></a>

More info:
- https://en.wikipedia.org/wiki/Orthogonal_matrix

In [15]:
# Q*QT = 1

EXAMPLE_1 = np.array([[1,0], [0,1]])
EXAMPLE_2 = np.array([[1,0], [0,-1]])
EXAMPLE_3 = np.array([[0.96, 0.28], [ -0.28, 0.96]])

print ("Example v1 (Identity Transformation):\n", EXAMPLE_1)
print ("Example v2 (Reflection across x-axis):\n", EXAMPLE_2)
print ("Example v3 (Rotation by N degree):\n", EXAMPLE_3)
print ("\nPorperty verification:\n")
print ("PROPERTY #1: QQT == QTQ = I")
print ("Q*QT:\n", np.dot(EXAMPLE_3, EXAMPLE_3.T))
print ("QT*Q:\n", np.dot(EXAMPLE_3.T, EXAMPLE_3))
print ("\nPROPERTY #2: QT == QINV")
print ("Q.T:\n", EXAMPLE_3.T)
print ("Q.INV:\n",np.linalg.inv(EXAMPLE_3))

Example v1 (Identity Transformation):
 [[1 0]
 [0 1]]
Example v2 (Reflection across x-axis):
 [[ 1  0]
 [ 0 -1]]
Example v3 (Rotation by N degree):
 [[ 0.96  0.28]
 [-0.28  0.96]]

Porperty verification:

PROPERTY #1: QQT == QTQ = I
Q*QT:
 [[ 1.00000000e+00 -2.32702746e-17]
 [-2.32702746e-17  1.00000000e+00]]
QT*Q:
 [[1.00000000e+00 2.32702746e-17]
 [2.32702746e-17 1.00000000e+00]]

PROPERTY #2: QT == QINV
Q.T:
 [[ 0.96 -0.28]
 [ 0.28  0.96]]
Q.INV:
 [[ 0.96 -0.28]
 [ 0.28  0.96]]


### Matrix Inverse <a class="anchor" id="matrix-inverse"></a>

More info:
- https://en.wikipedia.org/wiki/Invertible_matrix
- http://mathworld.wolfram.com/MatrixInverse.html

In [16]:
# Successful example.
# M_wf stands for Matrix_WellFormed

M_wf = np.arange(4).reshape(2,2)
print (M_wf)

try:
    INV_M = np.linalg.inv(M_wf)
    print (INV_M)
except np.linalg.LinAlgError:
    print ("Matrix can't be inverted")
    pass

[[0 1]
 [2 3]]
[[-1.5  0.5]
 [ 1.   0. ]]


In [17]:
# Unsuccessful example.
# Matrix should be a Square to be invertible
# M_if stands for Matrix_IllFormed

M_if = np.arange(12).reshape(3,4)
print (M_if)

try:
    INV_M = np.linalg.inv(M_if)
    print (INV_M)
except np.linalg.LinAlgError:
    print ("Matrix can't be inverted")
    pass

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Matrix can't be inverted


### Matrix Product <a class="anchor" id="matrix-product"></a>

More info:
- https://en.wikipedia.org/wiki/Matrix_multiplication

In [18]:
X1 = np.arange(9).reshape(3,3)
X2 = np.arange(9).reshape(3,3)

print ("Matrix #1:\n", X1)
print ("\nMatrix #2:\n", X2)

print ("\nMatrix Product:\n", np.dot(X1, X2))

# In this second approach each element is multiplied by each element
# This is needed when we found some coefficients for x-es in matrix and we want to modify those based on newly found coefficients, in such case we don't need matrix product
print ("\nGeneral multiplication:\n", np.multiply(X1,X2))

Matrix #1:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

Matrix #2:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

Matrix Product:
 [[ 15  18  21]
 [ 42  54  66]
 [ 69  90 111]]

General multiplication:
 [[ 0  1  4]
 [ 9 16 25]
 [36 49 64]]


### Matrix and Vector norms <a class="anchor" id="matrix-vector-norms"></a>

More info:
- https://en.wikipedia.org/wiki/Norm_(mathematics)
- https://en.wikipedia.org/wiki/Matrix_norm

There are 3 main Norms.
- L^1: http://mathworld.wolfram.com/L1-Norm.html
- L^2: http://mathworld.wolfram.com/L2-Norm.html 
- L^Infinity: http://mathworld.wolfram.com/L-Infinity-Norm.html

In [19]:
F = (np.arange(9)-4).reshape(3,3)
print ("Original matrix:\n", F)

# Used when vector direction is important
print ("L^1 norm:")
print (np.linalg.norm(F,1))

# Euclidean (Frobenius) distance form origin to point X
print ("L^2 norm:")
print (np.linalg.norm(F,2))

print ("L^Infinity norm:")
print (np.linalg.norm(F,np.inf))

Original matrix:
 [[-4 -3 -2]
 [-1  0  1]
 [ 2  3  4]]
L^1 norm:
7.0
L^2 norm:
7.3484692283495345
L^Infinity norm:
9.0


### Eigendecomposition (Eigenvectors, Eigenvalues) <a class="anchor" id="eigendecomposition"></a>

More info:
- https://en.wikipedia.org/wiki/Eigendecomposition_of_a_matrix

In [20]:
# NOTE: Matrix should be Square to be eigendecomposable!
G = np.array([[1,2,3],[3,2,1],[1,0,-1]])
print ("Original matrix:\n", G)

# Click LMB on 'eig' function and press Shift+Tab to see additional info and explanation on return values
eigenvalues, eigenvectors = np.linalg.eig(G)

print ("\nEigenvalues (Scales of orthonormal vectors):\n", eigenvalues)
print ("\nEigenvectors (Matrix with stacked orthonormal vectors):\n", eigenvectors)

print ("\nVERIFICATION: Main idea is that MATRIX*EigenVector is equal to EigenValue*EigenVector")

first_column = eigenvectors[:,0] # Get first column as slice
print ("\nProduct of Matrix and eigenvector column:\n", np.dot(G, first_column))
print ("\nProduct of eigenvalue and eigenvector:\n", eigenvalues[0] * first_column)

first_column = eigenvectors[:,1] # Get first column as slice
print ("\nProduct of Matrix and eigenvector column:\n", np.dot(G, first_column))
print ("\nProduct of eigenvalue and eigenvector:\n", eigenvalues[1] * first_column)

### This for some reason does not match.
first_column = eigenvectors[:,2] # Get first column as slice
print ("\nProduct of Matrix and eigenvector column:\n", np.dot(G, first_column))
print ("\nProduct of eigenvalue and eigenvector:\n", eigenvalues[2] * first_column)

Original matrix:
 [[ 1  2  3]
 [ 3  2  1]
 [ 1  0 -1]]

Eigenvalues (Scales of orthonormal vectors):
 [ 4.31662479e+00 -2.31662479e+00  1.47314580e-16]

Eigenvectors (Matrix with stacked orthonormal vectors):
 [[ 0.58428153  0.73595785  0.40824829]
 [ 0.80407569 -0.38198836 -0.81649658]
 [ 0.10989708 -0.55897311  0.40824829]]

VERIFICATION: Main idea is that MATRIX*EigenVector is equal to EigenValue*EigenVector

Product of Matrix and eigenvector column:
 [2.52212416 3.47089307 0.47438446]

Product of eigenvalue and eigenvector:
 [2.52212416 3.47089307 0.47438446]

Product of Matrix and eigenvector column:
 [-1.7049382   0.88492371  1.29493096]

Product of eigenvalue and eigenvector:
 [-1.7049382   0.88492371  1.29493096]

Product of Matrix and eigenvector column:
 [-2.22044605e-16  3.88578059e-16  2.77555756e-16]

Product of eigenvalue and eigenvector:
 [ 6.01409256e-17 -1.20281851e-16  6.01409256e-17]


### Matrix Trace <a class="anchor" id="matrix-trace"></a>

More info:
- https://en.wikipedia.org/wiki/Trace_(linear_algebra)

In [21]:
TRACE_E = np.array([[1,2,3],[1,-2,4],[0,-7,0]])
print ("Original matrix:\n", TRACE_E)
print ("Matrix trace:", TRACE_E.trace())

Original matrix:
 [[ 1  2  3]
 [ 1 -2  4]
 [ 0 -7  0]]
Matrix trace: -1


### Matrix Gradient <a class="anchor" id="matrix-gradient"></a>

More info:
- https://en.wikipedia.org/wiki/Matrix_calculus#Derivatives_with_matrices

<img src="https://wikimedia.org/api/rest_v1/media/math/render/svg/968417a1863243432c63633a4636c4bd94008643" />


In [22]:
# Vector gradient

grad_vec = np.array([1,2,4,7,11,16], dtype = np.float)
print ("Vector gradient: ", np.gradient(grad_vec))

Vector gradient:  [1.  1.5 2.5 3.5 4.5 5. ]


In [23]:
# Matrix gradient
GRAD_MAT = np.array([[1,2,3],[3,7,8]], dtype = np.float)
resulted_gradient = np.gradient(GRAD_MAT)
print ("Matrix gradient\n:", resulted_gradient)

Matrix gradient
: [array([[2., 5., 5.],
       [2., 5., 5.]]), array([[1. , 1. , 1. ],
       [4. , 2.5, 1. ]])]


### Hessian Matrix <a class="anchor" id="matrix-hessian"></a>

More info:
- https://en.wikipedia.org/wiki/Hessian_matrix
- https://en.wikipedia.org/wiki/Newton%27s_method

<img src="https://wikimedia.org/api/rest_v1/media/math/render/svg/af3268bb2afed0534da1e9493535b5ae1a5d08cc" />
Is used for <b>Second derivative test</b>

In [25]:
def hessian(x):
    """
    Calculate the hessian matrix with finite differences
    Parameters:
       - x : ndarray
    Returns:
       an array of shape (x.dim, x.ndim) + x.shape
       where the array[i, j, ...] corresponds to the second derivative x_ij
    """
    x_grad = np.gradient(x) 
    hessian = np.empty((x.ndim, x.ndim) + x.shape, dtype=x.dtype) 
    for k, grad_k in enumerate(x_grad):
        # iterate over dimensions
        # apply gradient again to every component of the first derivative.
        tmp_grad = np.gradient(grad_k) 
        for l, grad_kl in enumerate(tmp_grad):
            hessian[k, l, :, :] = grad_kl
    return hessian

x = np.random.randn(10, 10, 10)
hessian(x)

array([[[[[-1.57702711e+00, -2.10641031e-01, -2.21390980e-01, ...,
           -9.39806530e-01, -4.38738804e-01, -2.74183916e+00],
          [-4.38938510e-01,  1.54917459e+00, -2.16610288e-01, ...,
            1.15672082e+00,  2.01074452e+00,  2.99014269e-01],
          [-1.70671356e+00,  1.35561655e+00, -9.31908725e-01, ...,
           -2.44976331e+00, -6.00583986e-01, -1.67270307e+00],
          ...,
          [-1.31592423e+00,  4.73708857e-01,  1.84838268e+00, ...,
           -7.31399473e-01,  1.07767361e+00, -2.45647743e-02],
          [-5.05871672e-01,  1.20569354e+00,  1.21486708e-01, ...,
           -4.58606217e-01, -1.17675288e+00,  7.11724399e-04],
          [ 4.12805400e-01, -7.97873963e-01, -5.41367735e-01, ...,
            1.18810428e+00, -8.03683256e-01, -5.83589364e-01]],

         [[ 1.26180062e-01, -1.54075915e-01, -6.86191151e-01, ...,
           -3.67768458e-01, -1.02193598e+00, -1.89703150e+00],
          [ 1.13810771e+00,  9.31492507e-01, -1.23230863e+00, ...,
      

## Resources <a class="anchor" id="resources"></a>
- <a href="http://ocdevel.com/mlg/8">Machine Learning Guide podcast, on Math</a>
- <a href="https://www.hackerrank.com/domains/mathematics?filters[subdomains][0]=linear-algebra-foundations">HackerRank Mathematical Challenges</a>
- <a href="https://www.khanacademy.org/math">Khan Academy, Math section</a>
- <a href="https://brilliant.org/">Brilliant</a>
- <a href="https://www.wolframalpha.com/">WolframAlpha</a>



Created by <a class="reference external" href="https://www.facebook.com/vladyslav.elashevskyy">Vladyslav Ieliashevskyi</a> in April 2019, based on second lecture of Lviv Data Science School 2019, performed by <a class="reference external" href="https://www.facebook.com/oleksandr.gurbych">Oleksandr Gurbych</a>

This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/3.0/deed.en_US">Creative Commons Attribution 3.0 Unported License</a>